name: desinsetizadora
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: 0.12.0+1
  shared_preferences: 0.4.2
  dio: ^2.1.0
  rxdart: ^0.20.0
  flutter_calendar: ^0.0.8
  floating_action_row: ^0.0.3


  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
