CREATE TABLE LOGIN(
   ID   INT              NOT NULL,
   EMAIL VARCHAR (100)     NOT NULL,
   SENHA  VARCHAR(50)          NOT NULL,
   NOME  VARCHAR(100)          NOT NULL,     
   PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
   ID   INT              NOT NULL,
   NOME VARCHAR (100)     NOT NULL,
   TELEFONE  VARCHAR(50)             ,
   ENDERECO  VARCHAR (100) ,
   MAX_ARMADILHAS   INT,
   ID_RESPONSAVEL   INT  ,
   PRIMARY KEY (ID)
);

CREATE TABLE VISITA(
   ID   INT              NOT NULL,
   DATA DATETIME     NOT NULL,
   ID_CLIENTE  INT              NOT NULL,
   HORA_INICIO  DATETIME,
   HORA_FIM   DATETIME,
   PRIMARY KEY (ID)
);

CREATE TABLE ARMADILHAS_VISITA(
   ID  INT              NOT NULL,
   ID_ARMADILHA   INT              NOT NULL,
   ID_CLIENTE INT    NOT NULL,
   ID_VISITA INT NOT NULL,
   STATUS_ANTIGO VARCHAR(50) NOT NULL,
   STATUS_NOVO VARCHAR(50) NOT NULL,
   POSICAO VARCHAR(50) NOT NULL,
   DATA VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE ARMADILHAS_CLIENTES(
    ID INT NOT NULL,
   ID_ARMADILHA INT NOT NULL,
   ID_CLIENTE INT NOT NULL,
   PRIMARY KEY (ID)

);

CREATE TABLE ARMADILHA(
    ID INT NOT NULL,
    NOME VARCHAR(100),
    OBS VARCHAR(500),
    SITUACAO VARCHAR(50),
    PRIMARY KEY (ID)
);